version: '3'

networks: 
  postgres-compose-network:
    driver: bridge

services:

  postgres-compose:
    image: postgres:12.2
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network  
 
  pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 15432:80
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
